import { StyleSheet } from "react-native";

export default StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#F8F5FF",
  },
  topBar: {
    height: 60,
    backgroundColor: "#FFF",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 20,
    borderBottomWidth: 1,
    borderBottomColor: "#F0EBFB",
  },
  logoHeader: {
    width: 100,
    height: 35,
  },
  menuButton: {
    padding: 5,
  },
  scrollContent: {
    padding: 20,
  },
  heroSection: {
    marginBottom: 30,
  },
  badgeCount: {
    backgroundColor: "#EFE8FE",
    alignSelf: "flex-start",
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 20,
    marginBottom: 15,
  },
  badgeCountText: {
    color: "#6C38CC",
    fontSize: 12,
    fontWeight: "bold",
  },
  heroTitle: {
    fontSize: 30,
    fontWeight: "bold",
    color: "#111",
    lineHeight: 36,
    marginBottom: 12,
  },
  heroTitleHighlight: {
    color: "#6C38CC",
  },
  heroSub: {
    fontSize: 14,
    color: "#666",
    lineHeight: 20,
    marginBottom: 20,
  },
  btnPrimary: {
    backgroundColor: "#7A33D4",
    height: 50,
    borderRadius: 25,
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    gap: 8,
    marginBottom: 10,
  },
  btnPrimaryText: {
    color: "#FFF",
    fontWeight: "bold",
    fontSize: 15,
  },
  btnSecondary: {
    backgroundColor: "#FFF",
    height: 50,
    borderRadius: 25,
    borderWidth: 1,
    borderColor: "#E2D3FA",
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    gap: 8,
  },
  btnSecondaryText: {
    color: "#7A33D4",
    fontWeight: "bold",
    fontSize: 15,
  },
  sectionHeader: {
    marginBottom: 15,
  },
  sectionTitle: {
    fontSize: 22,
    fontWeight: "bold",
    color: "#111",
  },
  sectionSub: {
    fontSize: 13,
    color: "#777",
    marginTop: 2,
  },
  card: {
    backgroundColor: "#FFF",
    borderRadius: 20,
    overflow: "hidden",
    marginBottom: 20,
    elevation: 3,
    shadowColor: "#000",
    shadowOpacity: 0.08,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: 4 },
  },
  cardImageArea: {
    height: 180,
    position: "relative",
  },
  cardImage: {
    width: "100%",
    height: "100%",
  },
  superBadge: {
    position: "absolute",
    top: 12,
    left: 12,
    backgroundColor: "#FFC400",
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 12,
  },
  superBadgeText: {
    fontSize: 11,
    fontWeight: "bold",
    color: "#333",
  },
  favoriteButton: {
    position: "absolute",
    top: 12,
    right: 12,
    backgroundColor: "rgba(255,255,255,0.9)",
    width: 32,
    height: 32,
    borderRadius: 16,
    justifyContent: "center",
    alignItems: "center",
  },
  cardBody: {
    padding: 16,
  },
  cardRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  cardNome: {
    fontSize: 18,
    fontWeight: "bold",
    color: "#222",
  },
  notaArea: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
  },
  cardNota: {
    fontSize: 14,
    fontWeight: "bold",
    color: "#333",
  },
  localArea: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    marginVertical: 6,
  },
  cardLocal: {
    fontSize: 12,
    color: "#777",
  },
  tagsRow: {
    flexDirection: "row",
    gap: 6,
    marginVertical: 10,
  },
  tagBadge: {
    backgroundColor: "#F0EBFB",
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 12,
  },
  tagText: {
    fontSize: 11,
    color: "#6C38CC",
    fontWeight: "600",
  },
  cardFooter: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginTop: 8,
    paddingTop: 10,
    borderTopWidth: 1,
    borderTopColor: "#F5F5F5",
  },
  cardPrecoLabel: {
    fontSize: 12,
    color: "#888",
  },
  cardPreco: {
    fontSize: 16,
    fontWeight: "bold",
    color: "#111",
  },
  cardAvaliacoes: {
    fontSize: 11,
    color: "#999",
  },
});